### PR TITLE
feat(formula): add some lookup formulas

### PR DESCRIPTION
**Pull request by wpxp123456**
close https://github.com/dream-num/univer-pro/issues/2364

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Review by Dushusir — APPROVED** [review]

**Comment by zhaolixin7** [comment]
@wpxp123456 drop删除引用值预期报#ref
image
[2024_9_7 14_59_17 commands.json](https://github.com/user-attachments/files/16915198/2024_9_7.14_59_17.commands.json)
[2024_9_7 14_59_17 video.webm](https://github.com/user-attachments/assets/adcb366e-2025-466b-bc86-f7e6b1f55f39)

**Comment by zhaolixin7** [comment]
EXPAND1、参数未空时无报错
image

**Comment by zhaolixin7** [comment]
TOCOL：选中公式结果后下拉填充，填充后删除选中单元格，公式结果未显示全
[2024_9_9 14_26_40 commands.json](https://github.com/user-attachments/files/16926323/2024_9_9.14_26_40.commands.json)
[2024_9_9 14_26_40 video.webm](https://github.com/user-attachments/assets/acf51e8f-c019-427d-abcb-dda4797b848e)

**Comment by zhaolixin7** [comment]
tocol:1、引用选区时（=TOCOL(,B4:B8,A7:A10)）预期显示#value，表现：显示#n/a
image
image

**Comment by zhaolixin7** [comment]
torow：引用选区计算不出结果=TOROW((A1:A6, C1:F1, G3:G6), 1)
[2024_9_9 16_03_39 snapshot.json](https://github.com/user-attachments/files/16927373/2024_9_9.16_03_39.snapshot.json)
image

**Comment by zhaolixin7** [comment]
WRAPCOLS：引用选区计算不出结果=WRAPCOLS(B1:B15,H11:I13) 
image

**Comment by zhaolixin7** [comment]
WRAPCOLS：选区显示不出结果（=WRAPCOLS((A1:A6, C1:F1, G3:G6), 3)）image

**Pull request merged**
