### PR TITLE
feat(sheet): support undo and redo in sheet cell

### LINKED ISSUE #374: feature(sheet): support undo/redo in cell editing

### PR DESCRIPTION
**Pull request by Jocs**
- [x] support undo and redo in sheet cell close #374

### CODE REVIEW

**Review by wzhudev — APPROVED** [review]
LGTM

**Review by wzhudev — CHANGES_REQUESTED** [review]
Maybe we should clear undo redo stack for of editor when we close a sheet editor.

**Comment by Jocs** [comment]
> Maybe we should clear undo redo stack for of editor when we close a sheet editor.

Yeh, already empty undo\redo stack when close a sheet editor.

**Comment by Jocs** [comment]
@wzhudev Fixed undo redo menu item status error

**Review by wzhudev — APPROVED** [review]

**Pull request merged**
