### PR TITLE
feat(formula): add some math formulas

### PR DESCRIPTION
**Pull request by wpxp123456**
close https://github.com/dream-num/univer-pro/issues/2406

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Review by Dushusir — APPROVED** [review]

**Comment by oumomomo** [comment]
FACT函数

1、单元格内输入=FACT(A1:A2:A3)计算不出结果
image

**Comment by oumomomo** [comment]
FACTDOUBLE函数
 
1、单元格内输入=FACTDOUBLE(-1)，计算不出值
image

**Comment by oumomomo** [comment]
MINVERSE函数

1、单元格内输入=MINVERSE(A2:C4 )，我们计算结果跟google一致，跟excel不一样
image

**Comment by oumomomo** [comment]
MMULT
单元格内输入=MMULT({1,3;5,12},MUNIT(2))={1,3;5}，计算结果不一致
image

**Comment by oumomomo** [comment]
SERIESSUM函数
1、单元格内输入=SERIESSUM(A3,B4,90000,A2:B7)，计算结果未报错
样张：https://1drv.ms/x/c/c874bd32de218f8c/Efb4yh2Cq8hDigqRxBPfMZQBIRVAvfCFJzxLunMi7X1opg?e=0sQFAh
image

**Comment by oumomomo** [comment]
TEXT函数
1、单元格内输入=TEXT(DATE(YEAR(TODAY()),SEQUENCE(10,20),-1),"")，计算结果预期为空
image

**Pull request merged**
