### PR TITLE
fix(sheets-ui): error quit edit when set-range-values was called

### PR DESCRIPTION
**Pull request by weird94**
close https://github.com/dream-num/univer-pro/issues/2780
close https://github.com/dream-num/univer/issues/3374
close https://github.com/dream-num/univer-pro/issues/1696
close https://github.com/dream-num/univer/issues/3591
close https://github.com/dream-num/univer-pro/issues/2717

## Pull Request Checklist

- [x] Related tickets or issues have been linked in the PR description (or missing issue).
- [x] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [x] Unit tests have been added for the changes (if applicable).
- [x] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Comment by weird94** [comment]
> 2024_10_10 20_38_36 video.webm

fixed

**Comment by oumomomo** [comment]
https://github.com/dream-num/univer/issues/3374

在单元格内输入横向的超长内容，点击fx栏，编辑框内容展示不全
[2024_10_11 11_14_06 video.webm](https://github.com/user-attachments/assets/7279a9a7-23d3-4729-97e7-b3b1dcbfe198)

**Comment by oumomomo** [comment]
无法通过fx栏写入内容
[2024_10_11 11_16_54 video.webm](https://github.com/user-attachments/assets/fa3aa3fd-c919-41ca-8c5d-9c51fbdb3c8c)

**Comment by weird94** [comment]
> 无法通过fx栏写入内容 [2024_10_11 11_16_54 video.webm](https://github.com/user-attachments/assets/fa3aa3fd-c919-41ca-8c5d-9c51fbdb3c8c)

fixed

**Review by Jocs — APPROVED** [review]

**Pull request merged**
