### PR TITLE
fix(formula): reverse undo range list

### LINKED ISSUE #1957: [Bug] Formula calculation refers to a selection area. After deleting any column in the reference area and undoing it, the formula result is not restored.
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、单元格P1=公式SUM(A23:d28)，选中P1向右、向下填充
2、删除B列后undo undo

### 预期行为

 P1单元格向右、向下填充的公式正常显示为公式

### 实际行为

undo后公式只显示值未显示结果
[2024_4_17 20_12_41 video.webm](https://github.com/dream-num/univer/assets/154207126/268da6e1-641c-4313-91d0-cd91d086084f)

### 运行环境

_No response_

### 系统信息

_No response_

### LINKED ISSUE #2311: [Bug] When there is a formula in a row, the row cannot be deleted successfully.
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.11

### Reproduction link

https://univer.ai/zh-CN/playground

### Expected behavior

可以正常删除

### Actual behavior

删除不成功，删除另外一行的公式，前一行的公式又出现

### System information

_No response_

### PR DESCRIPTION
**Pull request by Dushusir**
- [x] close #1957
- [x] close #2311
- [x] fix move selection after save formula editor 

如何测试？
输入公式 `=SUM(1)` 后，按`Enter`光标移动到下方，或者 `Tab` 后光标移动到右侧。原先是跳了2格。

## Pull Request Checklist

- [x] Related tickets or issues have been linked in the PR description (or missing issue).
- [x] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [x] Unit tests have been added for the changes (if applicable).
- [x] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Comment by zhaolixin7** [comment]
删除公式结果选区第一列后undo,undo后显示为值未显示为公式
[2024_6_3 11_34_02 video.webm](https://github.com/dream-num/univer/assets/154207126/d0df640a-8bd3-4b42-8497-a3f6afdea4bd)

**Comment by zhaolixin7** [comment]
@Dushusir 1、删除引用值然后进入编辑后退出，使用undo快捷键 表现：会进入编辑态
2、删除引用之后undo，表现:公式结果显示#ref。预期正确显示公式结果
[2024_6_4 15_17_53 commands.json](https://github.com/user-attachments/files/15544029/2024_6_4.15_17_53.commands.json)
[2024_6_4 15_17_53 video.webm](https://github.com/dream-num/univer/assets/154207126/28776b03-a065-44aa-b531-dd3c04f62d42)

**Comment by Dushusir** [comment]
> @Dushusir 1、删除引用值然后进入编辑后退出，使用undo快捷键 表现：会进入编辑态 2、删除引用之后undo，表现:公式结果显示#ref。预期正确显示公式结果 [2024_6_4 15_17_53 commands.json](https://github.com/user-attachments/files/15544029/2024_6_4.15_17_53.commands.json) [2024_6_4 15_17_53 video.webm](https://github.com/dream-num/univer/assets/154207126/28776b03-a065-44aa-b531-dd3c04f62d42)

1. dev下， 编辑单元格保存后，再撤销，也会出现`进入编辑`的情况，待主分支修复后复测
2. 已修复

**Comment by zhaolixin7** [comment]
@Dushusir  删除yi引用值结果计算错误
[2024_6_14 11_24_53 video.webm](https://github.com/dream-num/univer/assets/154207126/4d417649-4be4-4717-9ec4-d488f8f51ff3)

**Pull request merged**
