### PR TITLE
fix(sheet): insert wrong columns  when shift right

### LINKED ISSUE #2571: The function of Right Shift is not correct
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.15

### Reproduction link

1. choose two cells, and right click and select insert option.
2. then，select right shift.

### Expected behavior

only right shift 2 cells, not 18.

### Actual behavior

right shift 18 cells

### System information

System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 61.96 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    pnpm: 8.6.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.62
    Edge: 126.0.2592.61
    Safari: 17.5

### PR DESCRIPTION
**Pull request by yuhongz**
close #2571 

## Pull Request Checklist

- [x] Related tickets or issues have been linked in the PR description (or missing issue).
- [x] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [x] Unit tests have been added for the changes (if applicable).
- [x] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Review by wzhudev — APPROVED** [review]
LGTM

**Comment by wzhudev** [comment]
其实可以通过一些类型体操让 Tools.deepClone 脱掉外面那层 DeepReadonly

**Comment by yuhongz** [comment]
> 其实可以通过一些类型体操让 Tools.deepClone 脱掉外面那层 DeepReadonly

那应该要修改 deepClone 的 interface 吧？不过 deepClone 默认脱掉 readonly 符合其他场景的预期吗🤔

**Comment by oumomomo** [comment]
选中超链接&评论左侧的单元格使用右移，评论跟超链接未跟随移动
image

**Comment by yuhongz** [comment]
> 选中超链接&评论左侧的单元格使用右移，评论跟超链接未跟随移动 image

@oumomomo 这个情况需要提单给超链接和评论的 owner 看看，应该需要加监听或者 interceptor 之类的处理跟随移动

**Pull request merged**
