### PR TITLE
feat(formula): add some Text/Math/Lookup formulas

### LINKED ISSUE #2802: [Feature] More Text Formulas
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

[How to contribute formulas](https://univer.ai/guides/sheet/advanced/custom-formula#how-to-add-formulas-in-formula-engine)

#### Text formulas
- [x] REPT
- [x] TEXTAFTER
- [ ] TEXTBEFORE
- [ ] TEXTSPLIT
#### Math formulas
- [x] TRUNC
#### Lookup formulas
- [ ] AREAS
- [x] CHOOSECOLS
- [x] CHOOSEROWS
- [x] FILTER
- [x] HSTACK
- [x] VSTACK
- [x] SORT
- [x] SORTBY
- [x] TRANSPOSE
- [ ] UNIQUE

### PR DESCRIPTION
**Pull request by wpxp123456**
close #2802

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Comment by oumomomo** [comment]
输入=REPT("，，，",987654321)，计算结果展示为空单元格未报错
image

**Comment by oumomomo** [comment]
TEXTAFTER函数
输入=TEXTAFTER(A3,"红色",,FALSE)，A3单元格为空，错误码不一致
image

**Comment by oumomomo** [comment]
AREAS函数
1、
手动输入=AREAS((B2:D4,E5,F6:I9))，计算结果不出结果
image

**Comment by oumomomo** [comment]
FILTER函数
1、
输入=FILTER(A5:D20,C5:C20=H5,"")无法计算出值
image

**Comment by oumomomo** [comment]
FILTER函数
可复制样张的内容：https://dev.univer.plus/sheet/?unit=ZXTThy2MQl-5LuNMe0jIZQ&type=2&subunit=QFTlbrQA95aIDGHoprM53

1、
输入=SORT(FILTER(A5:D20,(C5:C20=H5)*(A5:A20=F5),""),4,-1)，单元格计算结果为空未报错
image

**Comment by oumomomo** [comment]
SORTBY函数
可用来复制的样张：https://dev.univer.plus/sheet/?unit=uaICHkclSwyqlXcfXsLmkQ&type=2&subunit=wxbCa8KjvnfGLmnaqHeZE
1、
输入：=SORTBY(A2:A9,1)，计算不出结果
image

**Comment by oumomomo** [comment]
除TEXTAFTER函数一个错误码问题，其他问题均已修复

输入=TEXTAFTER/TEXTBEFORE(A3,"红色",,FALSE)，A3单元格为空，错误码不一致
image

**Review by Dushusir — APPROVED** [review]

**Pull request merged**
