### PR TITLE
feat(i18n): add `fr-FR` locale

### PR DESCRIPTION
**Pull request by Blaked84**
This PR adds `fr-FR` (french) locale support to univer.
Most translations are AI-generated from `en-US`, but I reviewed most of them manually as a native French speaker.

**Remaining:**
- [x] UI translations
- [ ] Formula description translations

## Pull Request Checklist

- [x] Related tickets or issues have been linked in the PR description (or missing issue).
- [x] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [x] Unit tests have been added for the changes (if applicable).
- [x] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Comment by jikkai** [comment]
The translation of the formula's description presents some challenges. We are happy to merge your current pull request, allowing you to address the translation at a later time.

**Comment by Blaked84** [comment]
> The translation of the formula's description presents some challenges. We are happy to merge your current pull request, allowing you to address the translation at a later time.

Thanks @jikkai!
Yes, it's quite challenging. I wonder if the best approach would be to create a script that extracts the descriptions of formulas in each language from the Microsoft Excel help page. How do you usually handle this?

**Comment by jikkai** [comment]
I'm working on fixing some minor issues. Once complete, I'll merge the PR into the `dev` branch. Thank you again for your patience and assistance!

**Review by jikkai — APPROVED** [review]

**Comment by Blaked84** [comment]
@jikkai thank you very much for fixing the last issues 🙏
I was about to submit a fix for them.
Univer's team works so fast! 🤩

**Pull request merged**
