### PR TITLE
feat(formula): add some math function

### LINKED ISSUE #1809: [Feature] Math Formulas
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Math formula

### Solution

- [x] ASIN
- [x] ASINH
- [x] ATAN
- [x] ATAN2
- [x] ATANH
- [x] COS
- [x] TAN
- [x] TANH
- [x] ROUND
- [x] ROUNDDOWN
- [x] ROUNDUP
- [x] MROUND
- [x] CEILING.MATH
- [x] CEILING
- [x] CEILING.PRECISE
- [x] EXP
- [x] SIN
- [x] SINH
- [x] LOG
- [x] LOG10
- [x] FLOOR
- [x] FLOOR.MATH
- [x] FLOOR.PRECISE
- [x] DECIMAL
- [x] DEGREES
- [x] EVEN
- [x] ODD
- [x] LN
- [x] PI
- [x] RADIANS
- [x] RAND
- [x] RANDARRAY
- [x] RANDBETWEEN
- [x] SEC
- [x] SECH
- [x] SQRT
- [x] SQRTPI
- [x] SUMSQ
- [x] SUMX2MY2
- [x] SUMX2PY2
- [x] SUMXMY2

### PR DESCRIPTION
**Pull request by wpxp123456**
close #1809

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Review by Dushusir — APPROVED** [review]

**Comment by oumomomo** [comment]
EXP函数
输入=EXP(E21:E23)，删除引用列未报错
image

**Comment by oumomomo** [comment]
LOG10函数
输入=LOG10(E49:E51)后删除E列，错误码跟函数展示不对
image

**Comment by oumomomo** [comment]
FLOOR.PRECISE函数
输入=FLOOR.PRECISE(B1:B3)展示为值，google报错
image

**Comment by oumomomo** [comment]
DECIMAL函数
单元格内输入=DECIMAL("ceshi",15)可以计算出值，excel会报错
image

**Comment by oumomomo** [comment]
输入=PI()/1.570796327,1 计算结果错误
image

**Comment by oumomomo** [comment]
RAND函数
输入=RAND()100会计算出值，excel会报错
image

**Comment by oumomomo** [comment]
SECH函数
单元格内输入=SECH(2412414124)，计算结果 错误
image

**Comment by oumomomo** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> PI function Question 1: Input =PI()/1.570796327,1 & =PI()/1.570796327,M54 The calculation result is wrong, it is expected that an error code should be reported image image
> 
> Question 2: =PI()*(0^-1), error code inconsistency problem image
> 
> Question 3: =PI()*(0^0), the calculation results are inconsistent Enterprise WeChat screenshot_17213596693680

**Pull request merged**
