### PR TITLE
feat(formula): add some financial function

### LINKED ISSUE #2844: [Feature] More Financial Formulas
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

[How to contribute formulas](https://univer.ai/guides/sheet/advanced/custom-formula#how-to-add-formulas-in-formula-engine)

#### Financial formulas
- [x] ACCRINT
- [x] #2885
- [x] AMORLINC
- [x] COUPDAYBS
- [x] COUPDAYS
- [x] COUPDAYSNC
- [x] COUPNCD
- [x] COUPNUM
- [x] COUPPCD
- [x] CUMIPMT
- [x] CUMPRINC
- [x] DB
- [x] DDB
- [x] DISC
- [x] DOLLARDE
- [x] DOLLARFR
- [x] EFFECT
- [x] FV
- [x] FVSCHEDULE
- [x] INTRATE
- [x] IPMT
- [x] ISPMT
- [x] NOMINAL
- [x] NPER
- [x] PMT
- [x] PPMT
- [x] PV
- [x] RATE

### PR DESCRIPTION
**Pull request by wpxp123456**
close #2844
close https://github.com/dream-num/univer-pro/issues/1786
close https://github.com/dream-num/univer-pro/issues/1539
close https://github.com/dream-num/univer-pro/issues/1651
close https://github.com/dream-num/univer-pro/issues/2004

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Review by DR-Univer — APPROVED** [review]

**Comment by oumomomo** [comment]
AMORLINC函数
1、
输入=AMORLINC(40,1,1,1,1,1,4)，计算结果不一致
image

**Comment by oumomomo** [comment]
COUPDAYS函数
1、单元格内输入COUPDAYS(A2,A3,A4,A5)，计算结果错误
image

**Comment by oumomomo** [comment]
COUPNUM函数
1、单元格内输入=COUPNUM("2007/1/25","2008/11/15",2,1)，计算结果有误
image

**Comment by oumomomo** [comment]
RATE函数
1、输入=RATE(4*12, -200, 8000)*12，计算结果不一致
image

**Comment by oumomomo** [comment]
RATE函数
1、单元格内输入=RATE(0,-200,0)，计算结果有误
image

**Comment by oumomomo** [comment]
PPMT函数
单元格内输入=PPMT(100/1.2,1.6,0.1*1.1,50000)，计算结果不对
image

**Comment by oumomomo** [comment]
FVSCHEDULE函数
输入=FVSCHEDULE(1,{0.09,0.11,-1})，计算结果不对
image

**Comment by oumomomo** [comment]
FV函数：
输入=FV(4/12, 123, 9, 98)，后面几位计算结果不一致
image

**Comment by oumomomo** [comment]
DB函数
1、输入=DB(A1,A3,A4,2,7)，A1单元格为空
image

2、 =DB(10000000,1000000,6,7,7) ,参照google还是ecxel？
excel：
企业微信截图_17234563752340
google：
企业微信截图_17234563931052

**Comment by oumomomo** [comment]
CUMIPMT函数

输入=CUMIPMT(1/0.2,30*0.8,12,13,24,0)，计算结果有误
image

**Pull request merged**
