### PR TITLE
feat(sheets-ui): undo set cols visible should scroll to cols

### PR DESCRIPTION
**Pull request by wzhudev**
close https://github.com/dream-num/univer-pro/issues/2104

close #xxx

## Pull Request Checklist

- [x] Related tickets or issues have been linked in the PR description (or missing issue).
- [x] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [x] Unit tests have been added for the changes (if applicable).
- [x] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Comment by zhaolixin7** [comment]
@wzhudev 隐藏行后取消定位到对应的行 
[2024_9_7 11_02_54 video.webm](https://github.com/user-attachments/assets/626a358d-4c6a-4d5c-a595-b9f0300f9ba5)
[2024_9_7 11_02_54 commands.json](https://github.com/user-attachments/files/16914139/2024_9_7.11_02_54.commands.json)

**Comment by wzhudev** [comment]
Made it work for rows too. Please verify that. @zhaolixin7

**Comment by zhaolixin7** [comment]
> Made it work for rows too. Please verify that. @zhaolixin7

@wzhudev 行列都不行了
[2024_9_7 17_26_19 video.webm](https://github.com/user-attachments/assets/345e96ea-262e-4d35-acfa-0ed58a26017a)
[2024_9_7 17_13_55 commands.json](https://github.com/user-attachments/files/16917295/2024_9_7.17_13_55.commands.json)

**Comment by wzhudev** [comment]
> > Made it work for rows too. Please verify that. @zhaolixin7
> 
> @wzhudev 行列都不行了 [2024_9_7 17_26_19 video.webm](https://github.com/user-attachments/assets/345e96ea-262e-4d35-acfa-0ed58a26017a) [2024_9_7 17_13_55 commands.json](https://github.com/user-attachments/files/16917295/2024_9_7.17_13_55.commands.json)

或者 @oumomomo 修改一下对 bug 的描述？这样我好知道到底哪些路径上应该跳转到被展开的位置

**Pull request merged**
