### PR TITLE
feat(formula): bycol/byrow/map/reduce/scan

### PR DESCRIPTION
**Pull request by wpxp123456**
close https://github.com/dream-num/univer-pro/issues/2343

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Review by Dushusir — APPROVED** [review]

**Comment by oumomomo** [comment]
单元格内输入=REDUCE(,A15:C15, LAMBDA(a,b,a+b^2)) ，计算结果不对
image

**Comment by oumomomo** [comment]
REDUCE函数
单元格内输入=REDUCE(, A2:C3, LAMBDA(a,b,a+b^2))，计算结果不对
image

**Comment by oumomomo** [comment]
SCAN函数
单元格内输入=SCAN(1,A1:D1,LAMBDA(a,b,a,b)) ，计算结果未报错
image

**Comment by wpxp123456** [comment]
> =BYCOL(A:C,LAMBDA(array, MAX(array)))

循环引用先不管

**Pull request merged**
