### PR TITLE
feat(formula): add MINIFS,AVERAGEIF,AVERAGEIFS functions

### LINKED ISSUE #1278: [Feature]删除公式后支持 undo
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

公式结果或值删除后undo,公式未恢复
路径：1、A1=sum(D:D),删除A列或D列
2、删除后恢复（undo）删除操作

### 解决方案

支持undo操作

### LINKED ISSUE #1393: [Feature] acot公式计算逻辑
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

1、单元格公式acot(-2)
image

### 解决方案

对齐google还是Excel?

### PR DESCRIPTION
**Pull request by Dushusir**
close #1393
close [#688](https://github.com/dream-num/univer-pro/issues/688)
close #1278 #1403 (以前PR修复)

- [x] MINIFS 
- [x] AVERAGEIF
- [x] AVERAGEIFS
- [x] COUNTIF
- [x] COUNTIFS
- [x] COUNTBLANK
- [x] MINA
- [x] MAXA
- [x] AVEDEV

## Pull Request Checklist

- [x] Related tickets or issues have been linked in the PR description (or missing issue).
- [x] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [x] Unit tests have been added for the changes (if applicable).
- [x] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Comment by oumomomo** [comment]
MINIFS函数
image
excel：
image

**Comment by oumomomo** [comment]
MINIFS函数
image
excel：
image

**Comment by oumomomo** [comment]
AVERAGEIF函数：
=AVERAGEIF(A2:A6,"<>*（新办事处）",B2:B6)无法计算出值
image

**Comment by oumomomo** [comment]
AVERAGEIF函数
1、=AVERAGEIF(A2:A5,">250000",B2:B5)，excel计算报错
image

**Comment by oumomomo** [comment]
COUNTBLANK函数：
1、
删除COUNTBLANK引用的列，未报错显示为0
image

**Comment by oumomomo** [comment]
AVEDEV函数错误码问题
image

**Comment by Dushusir** [comment]
all fixed

**Pull request merged**
