### PR TITLE
chore: migrate to eslint 8+

### PR DESCRIPTION
**Pull request by jikkai**
- [x] I am sure that the code is update-to-date with the `dev` branch.

---

## What's new

- eslint support for yaml
- enforce json sorting
- no more prettier
- abstract tsconfig configuration in **common/infra**, will support **vite.config.ts** in the future
- no more f🤬king `references` in **tsconfig.json**

> Additional note: @univerjs/create-cli@0.5.0 already includes support for this version.

### CODE REVIEW

**Review by Dushusir — APPROVED** [review]

**Comment by wzhudev** [comment]
Gonna review this tonight.

**Comment by wzhudev** [comment]
Gonna review this tonight.

**Comment by wzhudev** [comment]
Gonna review this tonight.

**Review by wzhudev — APPROVED** [review]
LGTM

**Pull request merged**
