### PR TITLE
fix(sheets-ui): after unhiding row or col icon doesn't disappear

### LINKED ISSUE #2063: [Bug] After hiding a row and then unhiding it, the icon does not disappear.
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：
1、隐藏行
2、取消隐藏
3、检查icon

### Expected behavior

取消隐藏后，取消隐藏的icon应消失

### Actual behavior

取消隐藏后，取消隐藏的icon未消失

image
https://github.com/dream-num/univer/assets/167171356/7da200d6-6cfd-4b2e-aabc-ebe56cc5a3e9

### System information

_No response_

### PR DESCRIPTION
**Pull request by kovsu**
close #2063

before:

https://github.com/dream-num/univer/assets/82451257/4738454f-0fed-44cc-9379-b089fe4fe7ed

after:

https://github.com/dream-num/univer/assets/82451257/e367dfa7-79d8-484e-9db8-4a0794febd7c

### CODE REVIEW

**Comment by oumomomo** [comment]
同时设置多个隐藏行时，还是有问题

https://github.com/dream-num/univer/assets/167171356/cf1b0aac-52fe-438c-b209-a402a8be2aab

**Comment by wzhudev** [comment]
@kovsu Thanks for opening this PR! 

Univer uses a model -> rendering approach. After some investigation, I noticed that `_clearShapes` is not invoked in `_update` when a related mutation is triggered: https://github.com/dream-num/univer/blob/1f03b7a33975d0c8e4203c962a4aadd6e5b5240e/packages/sheets-ui/src/controllers/header-unhide.render-controller.ts#L103

If you would like to make a more proper fix, we would be very happy to merge this PR. Thanks for your effort! :heart:

**Review by wzhudev — CHANGES_REQUESTED** [review]
Should use another approach. Thanks!

**Comment by kovsu** [comment]
> Should use another approach. Thanks!

明天修 ：）

**Comment by kovsu** [comment]
@oumomomo 这样是正常的吧

https://github.com/dream-num/univer/assets/82451257/46caf1e1-4d0a-4bf7-a8cd-e4bdd8c03046

**Review by wzhudev — APPROVED** [review]

**Pull request merged**
