### PR TITLE
fix(formula): some formulas need to be tested in dev

### PR DESCRIPTION
**Pull request by wpxp123456**
test in https://univer-preview.vercel.app/sheets/

- [x] ROUNDBANK
- [x] ISBETWEEN
- [x] AVERAGE.WEIGHTED
- [x] MARGINOFERROR
- [x] ISEMAIL
- [x] ISURL
- [x] ENCODEURL
- [x] EPOCHTODATE
- [x] TO_DATE
- [x] ISDATE
- [x] LINEST
- [x] LOGEST
- [x] TREND
- [x] ARRAY_CONSTRAIN
- [x] FLATTEN
- [x] IMCOTH
- [x] IMLOG
- [x] IMTANH

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Comment by oumomomo** [comment]
单元格内输入=ROUNDBANK(523,10000)，计算结果错误
image

**Comment by jikkai** [comment]
Mark as draft

**Comment by oumomomo** [comment]
ISBETWEEN函数
单元格内输入=ISBETWEEN(0,"AA",1,1,FALSE),错误码不对
企业微信截图_17326893133267

**Comment by oumomomo** [comment]
AVERAGE.WEIGHTED函数
单元格内输入=AVERAGE.WEIGHTED(A1:A2, B1:B2, C1, C2)，计算不出结果
image

**Comment by oumomomo** [comment]
MARGINOFERROR函数
单元格内输入=MARGINOFERROR(A1:A2,B1)，计算结果不对
image

**Comment by oumomomo** [comment]
单元格内输入=ENCODEURL(A1:A2)，A1=1，A2=2   计算结果不对
image

**Comment by oumomomo** [comment]
TO_DATE函数
单元格内输入=TO_DATE(A1),按照图片内单元格的内容下拉填充，计算结果均不对
image

**Comment by oumomomo** [comment]
LINEST函数
计算结果不对
样张：https://dev.univer.plus/sheet/?unit=9s3w2aVWQgeD08MpYM0paw&type=2&subunit=8La2fPi3UBAG6UxMGyVY9
image

**Comment by oumomomo** [comment]
LINEST函数
单元格内输入=LINEST(2,2,20,FALSE)。计算不出结果
image

**Comment by oumomomo** [comment]
ARRAY_CONSTRAIN函数

1、在单元格内输入=ARRAY_CONSTRAIN(A1:C1, 2, 3)，单元格为空时计算结果也为空
image

**Comment by oumomomo** [comment]
FLATTEN函数

在单元格内输入=FLATTEN(A1:C10)，为空的单元格预期计算不出值
image

**Comment by oumomomo** [comment]
IMCOTH函数

单元格内输入=IMCOTH("0")，错误码不一致
image

**Comment by oumomomo** [comment]
单元格内输入=IMLOG(COMPLEX(0, 0), 2)，错误码不一致
image

**Comment by oumomomo** [comment]
单元格内输入=IMTANH(A1)，计算结果不对
image

**Review by Dushusir — APPROVED** [review]

**Pull request merged**
